sudo: required
services:
  - docker


before_install:
  - docker build -t shridhar/docker-react -f Dockerfile.dev .

script:
  - docker run shridhar/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker"
  env: "docker-env"
  bucket_name: "elasticbeanstalk-ap-south-1-743577097029"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
   
